credentials:
  usernames:
    kharazmico:
      email: kharazmico@gmail.com
      name: Kharazmico
      password: $2b$12$UoDrw11ayE9Sns9TEhyDGOBGLE.Z3..60l3YyLVeMclEqUTkBbpzS
    migholami101:
      email: migholami101@gmail.com
      name: Mina Gholami
      password: $2b$12$UoDrw11ayE9Sns9TEhyDGOBGLE.Z3..60l3YyLVeMclEqUTkBbpzS
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
